[2022-08-19 16:45:12,902] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-19T16:45:07.770848+00:00 [queued]>
[2022-08-19 16:45:13,181] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-19T16:45:07.770848+00:00 [queued]>
[2022-08-19 16:45:13,182] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 16:45:13,182] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-19 16:45:13,182] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 16:45:13,207] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-19 16:45:07.770848+00:00
[2022-08-19 16:45:13,221] {standard_task_runner.py:52} INFO - Started process 462 to run task
[2022-08-19 16:45:13,226] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-19T16:45:07.770848+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmp__8lg639', '--error-file', '/tmp/tmps51ohp1l']
[2022-08-19 16:45:13,230] {standard_task_runner.py:80} INFO - Job 119: Subtask validate
[2022-08-19 16:45:13,384] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-19T16:45:07.770848+00:00 [running]> on host 4669929d2114
[2022-08-19 16:45:13,628] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T16:45:07.770848+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T16:45:07.770848+00:00
[2022-08-19 16:45:14,294] {python.py:173} INFO - Done. Returned value was: None
[2022-08-19 16:45:14,310] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220819T164507, start_date=20220819T164512, end_date=20220819T164514
[2022-08-19 16:45:14,391] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 16:45:14,466] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
