[2022-08-19 16:24:44,683] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-19T16:24:39.208915+00:00 [queued]>
[2022-08-19 16:24:44,899] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-19T16:24:39.208915+00:00 [queued]>
[2022-08-19 16:24:44,899] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 16:24:44,899] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-19 16:24:44,899] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 16:24:44,920] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-19 16:24:39.208915+00:00
[2022-08-19 16:24:44,929] {standard_task_runner.py:52} INFO - Started process 80 to run task
[2022-08-19 16:24:44,933] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-19T16:24:39.208915+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmprejh96rh', '--error-file', '/tmp/tmpn07rfiij']
[2022-08-19 16:24:44,935] {standard_task_runner.py:80} INFO - Job 111: Subtask validate
[2022-08-19 16:24:45,042] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-19T16:24:39.208915+00:00 [running]> on host 4669929d2114
[2022-08-19 16:24:45,181] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T16:24:39.208915+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T16:24:39.208915+00:00
[2022-08-19 16:24:45,820] {python.py:173} INFO - Done. Returned value was: None
[2022-08-19 16:24:45,843] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220819T162439, start_date=20220819T162444, end_date=20220819T162445
[2022-08-19 16:24:45,878] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 16:24:45,924] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
