[2022-08-17 18:48:48,783] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:48:44.748132+00:00 [queued]>
[2022-08-17 18:48:48,972] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T18:48:44.748132+00:00 [queued]>
[2022-08-17 18:48:48,973] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:48:48,973] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-17 18:48:48,973] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 18:48:48,989] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 18:48:44.748132+00:00
[2022-08-17 18:48:48,998] {standard_task_runner.py:52} INFO - Started process 783 to run task
[2022-08-17 18:48:49,002] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T18:48:44.748132+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmpa3hqyhlz', '--error-file', '/tmp/tmpasi0_ev5']
[2022-08-17 18:48:49,003] {standard_task_runner.py:80} INFO - Job 43: Subtask validate
[2022-08-17 18:48:49,058] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T18:48:44.748132+00:00 [running]> on host d254c144b912
[2022-08-17 18:48:49,157] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T18:48:44.748132+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T18:48:44.748132+00:00
[2022-08-17 18:48:57,496] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 18:48:57,496] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 743ms/step
[2022-08-17 18:48:58,281] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 18:48:58,284] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 662ms/step
[2022-08-17 18:49:00,581] {logging_mixin.py:115} INFO - Something went wrongâ€¦. (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials k15-20020a1fa10f000000b0037613541b27sm11237040vke.39 - gsmtp')
[2022-08-17 18:49:00,581] {logging_mixin.py:115} INFO - NOT VERIFIED:  [('jennifer aniston', 'ja@mail.com')]
[2022-08-17 18:49:00,581] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 18:49:00,603] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T184844, start_date=20220817T184848, end_date=20220817T184900
[2022-08-17 18:49:00,750] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-17 18:49:00,789] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
