[2022-08-19 01:26:02,438] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-19T01:25:55.851995+00:00 [queued]>
[2022-08-19 01:26:02,635] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-19T01:25:55.851995+00:00 [queued]>
[2022-08-19 01:26:02,635] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 01:26:02,635] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-19 01:26:02,635] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 01:26:02,668] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-19 01:25:55.851995+00:00
[2022-08-19 01:26:02,679] {standard_task_runner.py:52} INFO - Started process 380 to run task
[2022-08-19 01:26:02,688] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-19T01:25:55.851995+00:00', '--job-id', '513', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmpd92o_ppd', '--error-file', '/tmp/tmpn8yd0n4h']
[2022-08-19 01:26:02,690] {standard_task_runner.py:80} INFO - Job 513: Subtask validate
[2022-08-19 01:26:02,838] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-19T01:25:55.851995+00:00 [running]> on host 8d6926cc8b63
[2022-08-19 01:26:03,059] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T01:25:55.851995+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T01:25:55.851995+00:00
[2022-08-19 01:26:10,337] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-19 01:26:10,339] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 722ms/step
[2022-08-19 01:26:10,796] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-19 01:26:10,796] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 321ms/step
[2022-08-19 01:26:13,807] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-19 01:26:13,807] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 427ms/step
[2022-08-19 01:26:14,532] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-19 01:26:14,532] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 567ms/step
[2022-08-19 01:26:15,638] {python.py:173} INFO - Done. Returned value was: None
[2022-08-19 01:26:15,666] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220819T012555, start_date=20220819T012602, end_date=20220819T012615
[2022-08-19 01:26:15,766] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 01:26:15,814] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
